/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OptimizeRouteImport } from './routes/optimize'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as OptimizeIndexRouteImport } from './routes/optimize.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as CareerIndexRouteImport } from './routes/career.index'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileRemindersRouteImport } from './routes/profile.reminders'
import { Route as ProfileGoalsRouteImport } from './routes/profile.goals'
import { Route as ProfileDetailsRouteImport } from './routes/profile.details'
import { Route as OptimizeSyntaxRouteImport } from './routes/optimize.syntax'
import { Route as OptimizeSecurityRouteImport } from './routes/optimize.security'
import { Route as OptimizeResultRouteImport } from './routes/optimize.result'
import { Route as OptimizeRefactorRouteImport } from './routes/optimize.refactor'
import { Route as OptimizePerformanceRouteImport } from './routes/optimize.performance'
import { Route as OptimizeEditorRouteImport } from './routes/optimize.editor'
import { Route as OptimizeDebugRouteImport } from './routes/optimize.debug'
import { Route as OptimizeCompareRouteImport } from './routes/optimize.compare'
import { Route as OptimizeBugsRouteImport } from './routes/optimize.bugs'
import { Route as Onboarding3RouteImport } from './routes/onboarding.3'
import { Route as Onboarding2RouteImport } from './routes/onboarding.2'
import { Route as Onboarding1RouteImport } from './routes/onboarding.1'
import { Route as LearnVideoRouteImport } from './routes/learn.video'
import { Route as LearnQuizRouteImport } from './routes/learn.quiz'
import { Route as LearnIntermediateRouteImport } from './routes/learn.intermediate'
import { Route as LearnImprovementRouteImport } from './routes/learn.improvement'
import { Route as LearnChallengeRouteImport } from './routes/learn.challenge'
import { Route as LearnBeginnerRouteImport } from './routes/learn.beginner'
import { Route as LearnBadgeRouteImport } from './routes/learn.badge'
import { Route as LearnAssessmentRouteImport } from './routes/learn.assessment'
import { Route as LearnAdvancedRouteImport } from './routes/learn.advanced'
import { Route as HomeSummaryRouteImport } from './routes/home.summary'
import { Route as HomeSearchRouteImport } from './routes/home.search'
import { Route as HomeNotificationsRouteImport } from './routes/home.notifications'
import { Route as HomeInsightsRouteImport } from './routes/home.insights'
import { Route as HomeHistoryRouteImport } from './routes/home.history'
import { Route as HomeDailyLearningRouteImport } from './routes/home.daily-learning'
import { Route as HomeCalendarRouteImport } from './routes/home.calendar'
import { Route as HomeAssistantRouteImport } from './routes/home.assistant'
import { Route as HomeAiRecommendRouteImport } from './routes/home.ai-recommend'
import { Route as CareerSkillsRouteImport } from './routes/career.skills'
import { Route as CareerResumeRouteImport } from './routes/career.resume'
import { Route as CareerJobsRouteImport } from './routes/career.jobs'
import { Route as CareerInterviewRouteImport } from './routes/career.interview'
import { Route as ProfileSettingsThemeRouteImport } from './routes/profile.settings.theme'
import { Route as ProfileSettingsPrivacyRouteImport } from './routes/profile.settings.privacy'
import { Route as ProfileSettingsHelpRouteImport } from './routes/profile.settings.help'
import { Route as ProfileSettingsAccountRouteImport } from './routes/profile.settings.account'
import { Route as ProfileSettingsAboutRouteImport } from './routes/profile.settings.about'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeRoute = OptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const OptimizeIndexRoute = OptimizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OptimizeRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRemindersRoute = ProfileRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileGoalsRoute = ProfileGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileDetailsRoute = ProfileDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ProfileRoute,
} as any)
const OptimizeSyntaxRoute = OptimizeSyntaxRouteImport.update({
  id: '/syntax',
  path: '/syntax',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeSecurityRoute = OptimizeSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeResultRoute = OptimizeResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeRefactorRoute = OptimizeRefactorRouteImport.update({
  id: '/refactor',
  path: '/refactor',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizePerformanceRoute = OptimizePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeEditorRoute = OptimizeEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeDebugRoute = OptimizeDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeCompareRoute = OptimizeCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => OptimizeRoute,
} as any)
const OptimizeBugsRoute = OptimizeBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => OptimizeRoute,
} as any)
const Onboarding3Route = Onboarding3RouteImport.update({
  id: '/onboarding/3',
  path: '/onboarding/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding2Route = Onboarding2RouteImport.update({
  id: '/onboarding/2',
  path: '/onboarding/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding1Route = Onboarding1RouteImport.update({
  id: '/onboarding/1',
  path: '/onboarding/1',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVideoRoute = LearnVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => LearnRoute,
} as any)
const LearnQuizRoute = LearnQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LearnRoute,
} as any)
const LearnIntermediateRoute = LearnIntermediateRouteImport.update({
  id: '/intermediate',
  path: '/intermediate',
  getParentRoute: () => LearnRoute,
} as any)
const LearnImprovementRoute = LearnImprovementRouteImport.update({
  id: '/improvement',
  path: '/improvement',
  getParentRoute: () => LearnRoute,
} as any)
const LearnChallengeRoute = LearnChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LearnRoute,
} as any)
const LearnBeginnerRoute = LearnBeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => LearnRoute,
} as any)
const LearnBadgeRoute = LearnBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAssessmentRoute = LearnAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAdvancedRoute = LearnAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => LearnRoute,
} as any)
const HomeSummaryRoute = HomeSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSearchRoute = HomeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNotificationsRoute = HomeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HomeRoute,
} as any)
const HomeInsightsRoute = HomeInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => HomeRoute,
} as any)
const HomeHistoryRoute = HomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDailyLearningRoute = HomeDailyLearningRouteImport.update({
  id: '/daily-learning',
  path: '/daily-learning',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCalendarRoute = HomeCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAssistantRoute = HomeAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAiRecommendRoute = HomeAiRecommendRouteImport.update({
  id: '/ai-recommend',
  path: '/ai-recommend',
  getParentRoute: () => HomeRoute,
} as any)
const CareerSkillsRoute = CareerSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => CareerRoute,
} as any)
const CareerResumeRoute = CareerResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => CareerRoute,
} as any)
const CareerJobsRoute = CareerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CareerRoute,
} as any)
const CareerInterviewRoute = CareerInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => CareerRoute,
} as any)
const ProfileSettingsThemeRoute = ProfileSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsPrivacyRoute = ProfileSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsHelpRoute = ProfileSettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsAccountRoute = ProfileSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsAboutRoute = ProfileSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProfileSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/home': typeof HomeRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/optimize': typeof OptimizeRouteWithChildren
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/career/interview': typeof CareerInterviewRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/resume': typeof CareerResumeRoute
  '/career/skills': typeof CareerSkillsRoute
  '/home/ai-recommend': typeof HomeAiRecommendRoute
  '/home/assistant': typeof HomeAssistantRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/daily-learning': typeof HomeDailyLearningRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/search': typeof HomeSearchRoute
  '/home/summary': typeof HomeSummaryRoute
  '/learn/advanced': typeof LearnAdvancedRoute
  '/learn/assessment': typeof LearnAssessmentRoute
  '/learn/badge': typeof LearnBadgeRoute
  '/learn/beginner': typeof LearnBeginnerRoute
  '/learn/challenge': typeof LearnChallengeRoute
  '/learn/improvement': typeof LearnImprovementRoute
  '/learn/intermediate': typeof LearnIntermediateRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/video': typeof LearnVideoRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/optimize/bugs': typeof OptimizeBugsRoute
  '/optimize/compare': typeof OptimizeCompareRoute
  '/optimize/debug': typeof OptimizeDebugRoute
  '/optimize/editor': typeof OptimizeEditorRoute
  '/optimize/performance': typeof OptimizePerformanceRoute
  '/optimize/refactor': typeof OptimizeRefactorRoute
  '/optimize/result': typeof OptimizeResultRoute
  '/optimize/security': typeof OptimizeSecurityRoute
  '/optimize/syntax': typeof OptimizeSyntaxRoute
  '/profile/details': typeof ProfileDetailsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/reminders': typeof ProfileRemindersRoute
  '/profile/settings': typeof ProfileSettingsRouteWithChildren
  '/career/': typeof CareerIndexRoute
  '/home/': typeof HomeIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/optimize/': typeof OptimizeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/settings/about': typeof ProfileSettingsAboutRoute
  '/profile/settings/account': typeof ProfileSettingsAccountRoute
  '/profile/settings/help': typeof ProfileSettingsHelpRoute
  '/profile/settings/privacy': typeof ProfileSettingsPrivacyRoute
  '/profile/settings/theme': typeof ProfileSettingsThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/career/interview': typeof CareerInterviewRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/resume': typeof CareerResumeRoute
  '/career/skills': typeof CareerSkillsRoute
  '/home/ai-recommend': typeof HomeAiRecommendRoute
  '/home/assistant': typeof HomeAssistantRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/daily-learning': typeof HomeDailyLearningRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/search': typeof HomeSearchRoute
  '/home/summary': typeof HomeSummaryRoute
  '/learn/advanced': typeof LearnAdvancedRoute
  '/learn/assessment': typeof LearnAssessmentRoute
  '/learn/badge': typeof LearnBadgeRoute
  '/learn/beginner': typeof LearnBeginnerRoute
  '/learn/challenge': typeof LearnChallengeRoute
  '/learn/improvement': typeof LearnImprovementRoute
  '/learn/intermediate': typeof LearnIntermediateRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/video': typeof LearnVideoRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/optimize/bugs': typeof OptimizeBugsRoute
  '/optimize/compare': typeof OptimizeCompareRoute
  '/optimize/debug': typeof OptimizeDebugRoute
  '/optimize/editor': typeof OptimizeEditorRoute
  '/optimize/performance': typeof OptimizePerformanceRoute
  '/optimize/refactor': typeof OptimizeRefactorRoute
  '/optimize/result': typeof OptimizeResultRoute
  '/optimize/security': typeof OptimizeSecurityRoute
  '/optimize/syntax': typeof OptimizeSyntaxRoute
  '/profile/details': typeof ProfileDetailsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/reminders': typeof ProfileRemindersRoute
  '/profile/settings': typeof ProfileSettingsRouteWithChildren
  '/career': typeof CareerIndexRoute
  '/home': typeof HomeIndexRoute
  '/learn': typeof LearnIndexRoute
  '/optimize': typeof OptimizeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/settings/about': typeof ProfileSettingsAboutRoute
  '/profile/settings/account': typeof ProfileSettingsAccountRoute
  '/profile/settings/help': typeof ProfileSettingsHelpRoute
  '/profile/settings/privacy': typeof ProfileSettingsPrivacyRoute
  '/profile/settings/theme': typeof ProfileSettingsThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/home': typeof HomeRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/optimize': typeof OptimizeRouteWithChildren
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/career/interview': typeof CareerInterviewRoute
  '/career/jobs': typeof CareerJobsRoute
  '/career/resume': typeof CareerResumeRoute
  '/career/skills': typeof CareerSkillsRoute
  '/home/ai-recommend': typeof HomeAiRecommendRoute
  '/home/assistant': typeof HomeAssistantRoute
  '/home/calendar': typeof HomeCalendarRoute
  '/home/daily-learning': typeof HomeDailyLearningRoute
  '/home/history': typeof HomeHistoryRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/search': typeof HomeSearchRoute
  '/home/summary': typeof HomeSummaryRoute
  '/learn/advanced': typeof LearnAdvancedRoute
  '/learn/assessment': typeof LearnAssessmentRoute
  '/learn/badge': typeof LearnBadgeRoute
  '/learn/beginner': typeof LearnBeginnerRoute
  '/learn/challenge': typeof LearnChallengeRoute
  '/learn/improvement': typeof LearnImprovementRoute
  '/learn/intermediate': typeof LearnIntermediateRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/video': typeof LearnVideoRoute
  '/onboarding/1': typeof Onboarding1Route
  '/onboarding/2': typeof Onboarding2Route
  '/onboarding/3': typeof Onboarding3Route
  '/optimize/bugs': typeof OptimizeBugsRoute
  '/optimize/compare': typeof OptimizeCompareRoute
  '/optimize/debug': typeof OptimizeDebugRoute
  '/optimize/editor': typeof OptimizeEditorRoute
  '/optimize/performance': typeof OptimizePerformanceRoute
  '/optimize/refactor': typeof OptimizeRefactorRoute
  '/optimize/result': typeof OptimizeResultRoute
  '/optimize/security': typeof OptimizeSecurityRoute
  '/optimize/syntax': typeof OptimizeSyntaxRoute
  '/profile/details': typeof ProfileDetailsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/reminders': typeof ProfileRemindersRoute
  '/profile/settings': typeof ProfileSettingsRouteWithChildren
  '/career/': typeof CareerIndexRoute
  '/home/': typeof HomeIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/optimize/': typeof OptimizeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/settings/about': typeof ProfileSettingsAboutRoute
  '/profile/settings/account': typeof ProfileSettingsAccountRoute
  '/profile/settings/help': typeof ProfileSettingsHelpRoute
  '/profile/settings/privacy': typeof ProfileSettingsPrivacyRoute
  '/profile/settings/theme': typeof ProfileSettingsThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/forgot'
    | '/home'
    | '/learn'
    | '/login'
    | '/optimize'
    | '/otp'
    | '/profile'
    | '/reset'
    | '/signup'
    | '/welcome'
    | '/career/interview'
    | '/career/jobs'
    | '/career/resume'
    | '/career/skills'
    | '/home/ai-recommend'
    | '/home/assistant'
    | '/home/calendar'
    | '/home/daily-learning'
    | '/home/history'
    | '/home/insights'
    | '/home/notifications'
    | '/home/search'
    | '/home/summary'
    | '/learn/advanced'
    | '/learn/assessment'
    | '/learn/badge'
    | '/learn/beginner'
    | '/learn/challenge'
    | '/learn/improvement'
    | '/learn/intermediate'
    | '/learn/quiz'
    | '/learn/video'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/optimize/bugs'
    | '/optimize/compare'
    | '/optimize/debug'
    | '/optimize/editor'
    | '/optimize/performance'
    | '/optimize/refactor'
    | '/optimize/result'
    | '/optimize/security'
    | '/optimize/syntax'
    | '/profile/details'
    | '/profile/goals'
    | '/profile/reminders'
    | '/profile/settings'
    | '/career/'
    | '/home/'
    | '/learn/'
    | '/optimize/'
    | '/profile/'
    | '/profile/settings/about'
    | '/profile/settings/account'
    | '/profile/settings/help'
    | '/profile/settings/privacy'
    | '/profile/settings/theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/otp'
    | '/reset'
    | '/signup'
    | '/welcome'
    | '/career/interview'
    | '/career/jobs'
    | '/career/resume'
    | '/career/skills'
    | '/home/ai-recommend'
    | '/home/assistant'
    | '/home/calendar'
    | '/home/daily-learning'
    | '/home/history'
    | '/home/insights'
    | '/home/notifications'
    | '/home/search'
    | '/home/summary'
    | '/learn/advanced'
    | '/learn/assessment'
    | '/learn/badge'
    | '/learn/beginner'
    | '/learn/challenge'
    | '/learn/improvement'
    | '/learn/intermediate'
    | '/learn/quiz'
    | '/learn/video'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/optimize/bugs'
    | '/optimize/compare'
    | '/optimize/debug'
    | '/optimize/editor'
    | '/optimize/performance'
    | '/optimize/refactor'
    | '/optimize/result'
    | '/optimize/security'
    | '/optimize/syntax'
    | '/profile/details'
    | '/profile/goals'
    | '/profile/reminders'
    | '/profile/settings'
    | '/career'
    | '/home'
    | '/learn'
    | '/optimize'
    | '/profile'
    | '/profile/settings/about'
    | '/profile/settings/account'
    | '/profile/settings/help'
    | '/profile/settings/privacy'
    | '/profile/settings/theme'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/forgot'
    | '/home'
    | '/learn'
    | '/login'
    | '/optimize'
    | '/otp'
    | '/profile'
    | '/reset'
    | '/signup'
    | '/welcome'
    | '/career/interview'
    | '/career/jobs'
    | '/career/resume'
    | '/career/skills'
    | '/home/ai-recommend'
    | '/home/assistant'
    | '/home/calendar'
    | '/home/daily-learning'
    | '/home/history'
    | '/home/insights'
    | '/home/notifications'
    | '/home/search'
    | '/home/summary'
    | '/learn/advanced'
    | '/learn/assessment'
    | '/learn/badge'
    | '/learn/beginner'
    | '/learn/challenge'
    | '/learn/improvement'
    | '/learn/intermediate'
    | '/learn/quiz'
    | '/learn/video'
    | '/onboarding/1'
    | '/onboarding/2'
    | '/onboarding/3'
    | '/optimize/bugs'
    | '/optimize/compare'
    | '/optimize/debug'
    | '/optimize/editor'
    | '/optimize/performance'
    | '/optimize/refactor'
    | '/optimize/result'
    | '/optimize/security'
    | '/optimize/syntax'
    | '/profile/details'
    | '/profile/goals'
    | '/profile/reminders'
    | '/profile/settings'
    | '/career/'
    | '/home/'
    | '/learn/'
    | '/optimize/'
    | '/profile/'
    | '/profile/settings/about'
    | '/profile/settings/account'
    | '/profile/settings/help'
    | '/profile/settings/privacy'
    | '/profile/settings/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  HomeRoute: typeof HomeRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  OptimizeRoute: typeof OptimizeRouteWithChildren
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  Onboarding1Route: typeof Onboarding1Route
  Onboarding2Route: typeof Onboarding2Route
  Onboarding3Route: typeof Onboarding3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize': {
      id: '/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof OptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/optimize/': {
      id: '/optimize/'
      path: '/'
      fullPath: '/optimize/'
      preLoaderRoute: typeof OptimizeIndexRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/reminders': {
      id: '/profile/reminders'
      path: '/reminders'
      fullPath: '/profile/reminders'
      preLoaderRoute: typeof ProfileRemindersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/goals': {
      id: '/profile/goals'
      path: '/goals'
      fullPath: '/profile/goals'
      preLoaderRoute: typeof ProfileGoalsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/details': {
      id: '/profile/details'
      path: '/details'
      fullPath: '/profile/details'
      preLoaderRoute: typeof ProfileDetailsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/optimize/syntax': {
      id: '/optimize/syntax'
      path: '/syntax'
      fullPath: '/optimize/syntax'
      preLoaderRoute: typeof OptimizeSyntaxRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/security': {
      id: '/optimize/security'
      path: '/security'
      fullPath: '/optimize/security'
      preLoaderRoute: typeof OptimizeSecurityRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/result': {
      id: '/optimize/result'
      path: '/result'
      fullPath: '/optimize/result'
      preLoaderRoute: typeof OptimizeResultRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/refactor': {
      id: '/optimize/refactor'
      path: '/refactor'
      fullPath: '/optimize/refactor'
      preLoaderRoute: typeof OptimizeRefactorRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/performance': {
      id: '/optimize/performance'
      path: '/performance'
      fullPath: '/optimize/performance'
      preLoaderRoute: typeof OptimizePerformanceRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/editor': {
      id: '/optimize/editor'
      path: '/editor'
      fullPath: '/optimize/editor'
      preLoaderRoute: typeof OptimizeEditorRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/debug': {
      id: '/optimize/debug'
      path: '/debug'
      fullPath: '/optimize/debug'
      preLoaderRoute: typeof OptimizeDebugRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/compare': {
      id: '/optimize/compare'
      path: '/compare'
      fullPath: '/optimize/compare'
      preLoaderRoute: typeof OptimizeCompareRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/optimize/bugs': {
      id: '/optimize/bugs'
      path: '/bugs'
      fullPath: '/optimize/bugs'
      preLoaderRoute: typeof OptimizeBugsRouteImport
      parentRoute: typeof OptimizeRoute
    }
    '/onboarding/3': {
      id: '/onboarding/3'
      path: '/onboarding/3'
      fullPath: '/onboarding/3'
      preLoaderRoute: typeof Onboarding3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/2': {
      id: '/onboarding/2'
      path: '/onboarding/2'
      fullPath: '/onboarding/2'
      preLoaderRoute: typeof Onboarding2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/1': {
      id: '/onboarding/1'
      path: '/onboarding/1'
      fullPath: '/onboarding/1'
      preLoaderRoute: typeof Onboarding1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/video': {
      id: '/learn/video'
      path: '/video'
      fullPath: '/learn/video'
      preLoaderRoute: typeof LearnVideoRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/quiz': {
      id: '/learn/quiz'
      path: '/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof LearnQuizRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/intermediate': {
      id: '/learn/intermediate'
      path: '/intermediate'
      fullPath: '/learn/intermediate'
      preLoaderRoute: typeof LearnIntermediateRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/improvement': {
      id: '/learn/improvement'
      path: '/improvement'
      fullPath: '/learn/improvement'
      preLoaderRoute: typeof LearnImprovementRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/challenge': {
      id: '/learn/challenge'
      path: '/challenge'
      fullPath: '/learn/challenge'
      preLoaderRoute: typeof LearnChallengeRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/beginner': {
      id: '/learn/beginner'
      path: '/beginner'
      fullPath: '/learn/beginner'
      preLoaderRoute: typeof LearnBeginnerRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/badge': {
      id: '/learn/badge'
      path: '/badge'
      fullPath: '/learn/badge'
      preLoaderRoute: typeof LearnBadgeRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/assessment': {
      id: '/learn/assessment'
      path: '/assessment'
      fullPath: '/learn/assessment'
      preLoaderRoute: typeof LearnAssessmentRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/advanced': {
      id: '/learn/advanced'
      path: '/advanced'
      fullPath: '/learn/advanced'
      preLoaderRoute: typeof LearnAdvancedRouteImport
      parentRoute: typeof LearnRoute
    }
    '/home/summary': {
      id: '/home/summary'
      path: '/summary'
      fullPath: '/home/summary'
      preLoaderRoute: typeof HomeSummaryRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/search': {
      id: '/home/search'
      path: '/search'
      fullPath: '/home/search'
      preLoaderRoute: typeof HomeSearchRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/notifications': {
      id: '/home/notifications'
      path: '/notifications'
      fullPath: '/home/notifications'
      preLoaderRoute: typeof HomeNotificationsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/insights': {
      id: '/home/insights'
      path: '/insights'
      fullPath: '/home/insights'
      preLoaderRoute: typeof HomeInsightsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/history': {
      id: '/home/history'
      path: '/history'
      fullPath: '/home/history'
      preLoaderRoute: typeof HomeHistoryRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/daily-learning': {
      id: '/home/daily-learning'
      path: '/daily-learning'
      fullPath: '/home/daily-learning'
      preLoaderRoute: typeof HomeDailyLearningRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/calendar': {
      id: '/home/calendar'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/assistant': {
      id: '/home/assistant'
      path: '/assistant'
      fullPath: '/home/assistant'
      preLoaderRoute: typeof HomeAssistantRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/ai-recommend': {
      id: '/home/ai-recommend'
      path: '/ai-recommend'
      fullPath: '/home/ai-recommend'
      preLoaderRoute: typeof HomeAiRecommendRouteImport
      parentRoute: typeof HomeRoute
    }
    '/career/skills': {
      id: '/career/skills'
      path: '/skills'
      fullPath: '/career/skills'
      preLoaderRoute: typeof CareerSkillsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/resume': {
      id: '/career/resume'
      path: '/resume'
      fullPath: '/career/resume'
      preLoaderRoute: typeof CareerResumeRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/jobs': {
      id: '/career/jobs'
      path: '/jobs'
      fullPath: '/career/jobs'
      preLoaderRoute: typeof CareerJobsRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/interview': {
      id: '/career/interview'
      path: '/interview'
      fullPath: '/career/interview'
      preLoaderRoute: typeof CareerInterviewRouteImport
      parentRoute: typeof CareerRoute
    }
    '/profile/settings/theme': {
      id: '/profile/settings/theme'
      path: '/theme'
      fullPath: '/profile/settings/theme'
      preLoaderRoute: typeof ProfileSettingsThemeRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/privacy': {
      id: '/profile/settings/privacy'
      path: '/privacy'
      fullPath: '/profile/settings/privacy'
      preLoaderRoute: typeof ProfileSettingsPrivacyRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/help': {
      id: '/profile/settings/help'
      path: '/help'
      fullPath: '/profile/settings/help'
      preLoaderRoute: typeof ProfileSettingsHelpRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/account': {
      id: '/profile/settings/account'
      path: '/account'
      fullPath: '/profile/settings/account'
      preLoaderRoute: typeof ProfileSettingsAccountRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/about': {
      id: '/profile/settings/about'
      path: '/about'
      fullPath: '/profile/settings/about'
      preLoaderRoute: typeof ProfileSettingsAboutRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
  }
}

interface CareerRouteChildren {
  CareerInterviewRoute: typeof CareerInterviewRoute
  CareerJobsRoute: typeof CareerJobsRoute
  CareerResumeRoute: typeof CareerResumeRoute
  CareerSkillsRoute: typeof CareerSkillsRoute
  CareerIndexRoute: typeof CareerIndexRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerInterviewRoute: CareerInterviewRoute,
  CareerJobsRoute: CareerJobsRoute,
  CareerResumeRoute: CareerResumeRoute,
  CareerSkillsRoute: CareerSkillsRoute,
  CareerIndexRoute: CareerIndexRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface HomeRouteChildren {
  HomeAiRecommendRoute: typeof HomeAiRecommendRoute
  HomeAssistantRoute: typeof HomeAssistantRoute
  HomeCalendarRoute: typeof HomeCalendarRoute
  HomeDailyLearningRoute: typeof HomeDailyLearningRoute
  HomeHistoryRoute: typeof HomeHistoryRoute
  HomeInsightsRoute: typeof HomeInsightsRoute
  HomeNotificationsRoute: typeof HomeNotificationsRoute
  HomeSearchRoute: typeof HomeSearchRoute
  HomeSummaryRoute: typeof HomeSummaryRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAiRecommendRoute: HomeAiRecommendRoute,
  HomeAssistantRoute: HomeAssistantRoute,
  HomeCalendarRoute: HomeCalendarRoute,
  HomeDailyLearningRoute: HomeDailyLearningRoute,
  HomeHistoryRoute: HomeHistoryRoute,
  HomeInsightsRoute: HomeInsightsRoute,
  HomeNotificationsRoute: HomeNotificationsRoute,
  HomeSearchRoute: HomeSearchRoute,
  HomeSummaryRoute: HomeSummaryRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface LearnRouteChildren {
  LearnAdvancedRoute: typeof LearnAdvancedRoute
  LearnAssessmentRoute: typeof LearnAssessmentRoute
  LearnBadgeRoute: typeof LearnBadgeRoute
  LearnBeginnerRoute: typeof LearnBeginnerRoute
  LearnChallengeRoute: typeof LearnChallengeRoute
  LearnImprovementRoute: typeof LearnImprovementRoute
  LearnIntermediateRoute: typeof LearnIntermediateRoute
  LearnQuizRoute: typeof LearnQuizRoute
  LearnVideoRoute: typeof LearnVideoRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnAdvancedRoute: LearnAdvancedRoute,
  LearnAssessmentRoute: LearnAssessmentRoute,
  LearnBadgeRoute: LearnBadgeRoute,
  LearnBeginnerRoute: LearnBeginnerRoute,
  LearnChallengeRoute: LearnChallengeRoute,
  LearnImprovementRoute: LearnImprovementRoute,
  LearnIntermediateRoute: LearnIntermediateRoute,
  LearnQuizRoute: LearnQuizRoute,
  LearnVideoRoute: LearnVideoRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface OptimizeRouteChildren {
  OptimizeBugsRoute: typeof OptimizeBugsRoute
  OptimizeCompareRoute: typeof OptimizeCompareRoute
  OptimizeDebugRoute: typeof OptimizeDebugRoute
  OptimizeEditorRoute: typeof OptimizeEditorRoute
  OptimizePerformanceRoute: typeof OptimizePerformanceRoute
  OptimizeRefactorRoute: typeof OptimizeRefactorRoute
  OptimizeResultRoute: typeof OptimizeResultRoute
  OptimizeSecurityRoute: typeof OptimizeSecurityRoute
  OptimizeSyntaxRoute: typeof OptimizeSyntaxRoute
  OptimizeIndexRoute: typeof OptimizeIndexRoute
}

const OptimizeRouteChildren: OptimizeRouteChildren = {
  OptimizeBugsRoute: OptimizeBugsRoute,
  OptimizeCompareRoute: OptimizeCompareRoute,
  OptimizeDebugRoute: OptimizeDebugRoute,
  OptimizeEditorRoute: OptimizeEditorRoute,
  OptimizePerformanceRoute: OptimizePerformanceRoute,
  OptimizeRefactorRoute: OptimizeRefactorRoute,
  OptimizeResultRoute: OptimizeResultRoute,
  OptimizeSecurityRoute: OptimizeSecurityRoute,
  OptimizeSyntaxRoute: OptimizeSyntaxRoute,
  OptimizeIndexRoute: OptimizeIndexRoute,
}

const OptimizeRouteWithChildren = OptimizeRoute._addFileChildren(
  OptimizeRouteChildren,
)

interface ProfileSettingsRouteChildren {
  ProfileSettingsAboutRoute: typeof ProfileSettingsAboutRoute
  ProfileSettingsAccountRoute: typeof ProfileSettingsAccountRoute
  ProfileSettingsHelpRoute: typeof ProfileSettingsHelpRoute
  ProfileSettingsPrivacyRoute: typeof ProfileSettingsPrivacyRoute
  ProfileSettingsThemeRoute: typeof ProfileSettingsThemeRoute
}

const ProfileSettingsRouteChildren: ProfileSettingsRouteChildren = {
  ProfileSettingsAboutRoute: ProfileSettingsAboutRoute,
  ProfileSettingsAccountRoute: ProfileSettingsAccountRoute,
  ProfileSettingsHelpRoute: ProfileSettingsHelpRoute,
  ProfileSettingsPrivacyRoute: ProfileSettingsPrivacyRoute,
  ProfileSettingsThemeRoute: ProfileSettingsThemeRoute,
}

const ProfileSettingsRouteWithChildren = ProfileSettingsRoute._addFileChildren(
  ProfileSettingsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileDetailsRoute: typeof ProfileDetailsRoute
  ProfileGoalsRoute: typeof ProfileGoalsRoute
  ProfileRemindersRoute: typeof ProfileRemindersRoute
  ProfileSettingsRoute: typeof ProfileSettingsRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileDetailsRoute: ProfileDetailsRoute,
  ProfileGoalsRoute: ProfileGoalsRoute,
  ProfileRemindersRoute: ProfileRemindersRoute,
  ProfileSettingsRoute: ProfileSettingsRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRouteWithChildren,
  ForgotRoute: ForgotRoute,
  HomeRoute: HomeRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  OptimizeRoute: OptimizeRouteWithChildren,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  Onboarding1Route: Onboarding1Route,
  Onboarding2Route: Onboarding2Route,
  Onboarding3Route: Onboarding3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
